### ISSUE TITLE
loss decreases slowly

### ISSUE THREAD

**Issue by GrassBro** [zhanggang001/RefineMask#1]
Hi, @zhanggang001 ,

Thanks for sharing your impressive work.

I implement your code to train my own dataset with 4 GPU cards. Since your code only supports one image per GPU, I guess it would be the reason why the loss decrease so slowly. So, I wonder to know when you could release the code supporting multiple images per GPU batch. 

Many thanks.

**Comment by zhanggang001** [comment]
Sorry, I am not sure and have no time now. Maybe after the May Day holiday. Actually, I think it should be easy for you to update the code to support multiple images per GPU batch.  I will update the code as soon as possible. Thank you for your interest in our work.

**Comment by zhanggang001** [comment]
The code supports multiple images per GPU batch now.
