### ISSUE TITLE
测试的时候不显示分割结果

### ISSUE THREAD

**Issue by qzsrh** [zhanggang001/RefineMask#11]
训练完毕进行测试的时候，测试展示的结果图仍让是原图，没有任何分割的结果，请问可能是什么原因造成的？

**Comment by zhanggang001** [comment]
什么数据集？COCO/LVIS/Cityscapes? 看一下训练崩了没？

**Comment by qzsrh** [comment]
Cityscapes数据集，测试的时候有警告：
/home/test/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

**Comment by zhanggang001** [comment]
这个应该没有影响
