### ISSUE TITLE
您好，实在抱歉，打扰您一下，refineMask代码我跑了好几天啦，但是总是出现一个问题：训练着训练着loss就为Nan啦，我也不知道哪里出了问题，想请教一下。我的环境是：3090的卡，cuda11.1，python3.8，torch1.8，gcc/g++7.5， mmdet2.3.0，mmcv-full1.0.5，COCO2017数据集，sample_per_gpu=1，lr=0.001

### ISSUE THREAD

**Issue by DongHappyyy** [zhanggang001/RefineMask#12]
[20210811_172739.log](https://github.com/zhanggang001/RefineMask/files/6972354/20210811_172739.log)
[20210811_213307.log](https://github.com/zhanggang001/RefineMask/files/6972356/20210811_213307.log)
[20210811_171330.log](https://github.com/zhanggang001/RefineMask/files/6972357/20210811_171330.log)

**Comment by zhanggang001** [comment]
> _No description provided._

Please upload the running log here.

**Comment by DongHappyyy** [comment]
> > _No description provided._
> 
> Please upload the running log here.

已经上传log啦，请多麻烦您给看一看，十分感谢

**Comment by zhanggang001** [comment]
> > > _No description provided._
> > 
> > 
> > Please upload the running log here.
> 
> 已经上传log啦，请多麻烦您给看一看，十分感谢

Only using one gpu cannot reproduce the result. If you need to use one gpu to train the model, decrease the lr to 0.0025 .

**Comment by DongHappyyy** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > Please upload the running log here.
> > 
> > 
> > 已经上传log啦，请多麻烦您给看一看，十分感谢
> 
> Only using one gpu cannot reproduce the result. If you need to use one gpu to train the model, decrease the lr to 0.0025 .

Thank you very much!   I will try it right now!

**Comment by sanmulab** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > Please upload the running log here.
> > > 
> > > 
> > > 已经上传log啦，请多麻烦您给看一看，十分感谢
> > 
> > 
> > Only using one gpu cannot reproduce the result. If you need to use one gpu to train the model, decrease the lr to 0.0025 .
> 
> Thank you very much! I will try it right now!

你好，我的环境跟你一样的，请问你复现代码成功了。我的环境在mmdet2.3.0一直训练不起来。然后我迁移代码到mm2.12.0版本训练了12轮，但是测试模型后没有效果，AP为0
