### ISSUE TITLE
改变可视化结果的颜色及字体

### ISSUE THREAD

**Issue by wanxinjun** [zhanggang001/RefineMask#13]
您好，我想把可视化结果中同一类别的不同实例改成不同颜色，以及检测框和文本的颜色，请问在哪个文件中设置的，谢谢

**Comment by zhanggang001** [comment]
> 您好，我想把可视化结果中同一类别的不同实例改成不同颜色，以及检测框和文本的颜色，请问在哪个文件中设置的，谢谢

Please refer to [mmdetection](https://github.com/open-mmlab/mmdetection) for more details. I do not change the code for visualization.
