### ISSUE TITLE
refinemask不支持多图测试吗

### ISSUE THREAD

**Issue by niecongchong** [zhanggang001/RefineMask#16]
在我阅读refinemask的测试代码时，我发现其并不支持batch>1的推理，是这样的吗

**Comment by zhanggang001** [comment]
Yes, RefineMask is modified from the codebase[ MMDetection](https://github.com/open-mmlab/mmdetection/), and MMDetection only supports 1 image per GPU during inference.

**Comment by zhanggang001** [comment]
> 在我阅读refinemask的测试代码时，我发现其并不支持batch>1的推理，是这样的吗

Yes, RefineMask is modified from the codebase MMDetection, and MMDetection only supports 1 image per GPU during inference.
