### ISSUE TITLE
Attribute error: list object has no attribute shape (occur during the evaluation after 12 epochs)

### ISSUE THREAD

**Issue by apanand14** [zhanggang001/RefineMask#17]
Hello,
I'm able to run refine mask successfully using mmcv-full 1.3.12 and mmdet - 2.6.0 on windows. It runs fine for training and giving the below error during evaluation after 12 epochs. If possible then can you help me out on this and let me know what mistake I'm doing particularly? Thank you in advance.
 
File "tools/test.py", line 241, in
main()
File "tools/test.py", line 206, in main
outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\apis\test.py", line 28, in single_gpu_test
result = model(return_loss=False, rescale=True, **data)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmcv\parallel\data_parallel.py", line 42, in forward
return super().forward(*inputs, **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
return self.module(*inputs[0], **kwargs[0])
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
return old_func(*args, **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\base.py", line 174, in forward
return self.forward_test(img, img_metas, **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\base.py", line 147, in forward_test
return self.simple_test(imgs[0], img_metas[0], **kwargs)
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\two_stage.py", line 182, in simple_test
return self.roi_head.simple_test(
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\roi_heads\standard_roi_head.py", line 264, in simple_test
segm_results = self.simple_test_mask(
File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\roi_heads\refine_roi_head.py", line 92, in simple_test_mask
if det_bboxes.shape[0] == 0:
**AttributeError: 'list' object has no attribute 'shape'**

**Comment by zhanggang001** [comment]
Have you ever modified the code?

**Comment by zhanggang001** [comment]
> Hello,
> I'm able to run refine mask successfully using mmcv-full 1.3.12 and mmdet - 2.6.0 on windows. It runs fine for training and giving the below error during evaluation after 12 epochs. If possible then can you help me out on this and let me know what mistake I'm doing particularly? Thank you in advance.
> 
> File "tools/test.py", line 241, in
> main()
> File "tools/test.py", line 206, in main
> outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\apis\test.py", line 28, in single_gpu_test
> result = model(return_loss=False, rescale=True, **data)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
> return forward_call(*input, **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmcv\parallel\data_parallel.py", line 42, in forward
> return super().forward(*inputs, **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
> return forward_call(*input, **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
> return old_func(*args, **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\base.py", line 174, in forward
> return self.forward_test(img, img_metas, **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\base.py", line 147, in forward_test
> return self.simple_test(imgs[0], img_metas[0], **kwargs)
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\detectors\two_stage.py", line 182, in simple_test
> return self.roi_head.simple_test(
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\roi_heads\standard_roi_head.py", line 264, in simple_test
> segm_results = self.simple_test_mask(
> File "C:\Users\anaconda3\envs\mmcv\lib\site-packages\mmdet\models\roi_heads\refine_roi_head.py", line 92, in simple_test_mask
> if det_bboxes.shape[0] == 0:
> **AttributeError: 'list' object has no attribute 'shape'**

Have you ever modified the code?

**Comment by apanand14** [comment]
Yes. Two minor changes I made.
1. In tools/train.py -> commented  this line model.int_weights() and
2. In configs/r50-refinemask-1x.py -> commneted this line init_cfg = dict(type='Pretrained', checkpoint='torchvision://resnet50')

Training works fine and decreases loss as expected with different optimizers. But It gives error on the evaluation part, which I mentioned above.

**Comment by zhanggang001** [comment]
> Yes. Two minor changes I made.
> 
> 1. In tools/train.py -> commented  this line model.int_weights() and
> 2. In configs/r50-refinemask-1x.py -> commneted this line init_cfg = dict(type='Pretrained', checkpoint='torchvision://resnet50')
> 
> Training works fine and decreases loss as expected with different optimizers. But It gives error on the evaluation part, which I mentioned above.

You cannot comment the code in this way, the imagenet pretrained model is needed to train the detection model.

**Comment by apanand14** [comment]
Yes. I'm aware of this. As I said I'm not having an issue in training part. I'm using pretrained torchvision resnet 50 . I commneted out in config file because it was used two times and no need of it  so. But why I'm getting erro in evaluation part that I'm not getting it.

**Comment by zhanggang001** [comment]
> Yes. I'm aware of this. As I said I'm not having an issue in training part. I'm using pretrained torchvision resnet 50 . I commneted out in config file because it was used two times and no need of it so. But why I'm getting erro in evaluation part that I'm not getting it.

Maybe you can use the released trained model to do inference first, if it has no problem, there may be something wrong with your training process.

**Comment by apanand14** [comment]
When I use model.init_weights()  then I get this error while training but when I comment that line then t doesn't throw any error and starts training. But I'm more concern about how should I resolve inference/evaluation error which I mentioned above.
  
File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 163, in main
    model.init_weights()
  File "C:\Users\topseven\anaconda3\envs\mmcv\lib\site-packages\mmcv\runner\base_module.py", line 117, in init_weights
    m.init_weights()
TypeError: init_weights() missing 1 required positional argument: 'pretrained'

**Comment by apanand14** [comment]
Hello @zhanggang001,

 I tried with the checkpoint r50-coco-1x.pth provided by you and did inference. It gives me the same error which I mentioned above. Also, I tried with my trained model as well and gives the same error during inference. 

Then, I trained mask rcnn without your additional implementation of refine mask. It does inference for images and got CUDA memory error (which I can understand) but not giving other errors means inference works with state of the art mask rcnn but not with the refine mask. 

It throws error while checking the condition "if det_bboxes.shape[0] == 0" particularly in refine_roi_head.py

Can you please assist me or check why it's happening in your implementation? Thank you in advance

**Comment by zhanggang001** [comment]
> Hello @zhanggang001,
> 
> I tried with the checkpoint r50-coco-1x.pth provided by you and did inference. It gives me the same error which I mentioned above. Also, I tried with my trained model as well and gives the same error during inference.
> 
> Then, I trained mask rcnn without your additional implementation of refine mask. It does inference for images and got CUDA memory error (which I can understand) but not giving other errors means inference works with state of the art mask rcnn but not with the refine mask.
> 
> It throws error while checking the condition "if det_bboxes.shape[0] == 0" particularly in refine_roi_head.py
> 
> Can you please assist me or check why it's happening in your implementation? Thank you in advance

Sorry that I can not help you more (I have no time to reproduce the error you encounter in your environment), I can only make sure that you can run RefineMask on the same environment with our released version. In other words, if you use the same environment, you can reproduce the result. But you run with different versions of mmdetection and mmcv, and even on Windows. I don't know what will happens.

**Comment by apanand14** [comment]
okay. No problem . thank you for your support. I will try with your versions as well and let you know how it goes.

**Comment by apanand14** [comment]
Hello @zhanggang001,

**Extension of Refine Mask implementation**

I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask with **224*224** final size? The reason behind this question was that I work on very high resolution images and I get good results compare to mask rcnn, detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.

Thank you for your time!

**Comment by zhanggang001** [comment]
Yeah, you can try that (add one more stage), but it will consume much more GPU memory.  Some tips to do that, using class-agnostic classifier in the stages with large spatial size; reducing the feature channel; only upsampling the boundary pixels;  etc.  Good luck.


Best regards,
-------------
Gang Zhang, PhD Student
Department of Computer Science and Technology
Tsinghua University, Beijing 100084, China
Tel: +86-15708328370
Mail: ***@***.***


On 09/21/2021 ***@***.***> wrote：

Hello @zhanggang001,

Extension of Refine Mask implementation

I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask 224*224 final size? The reason behind this question was that I get good results compare to mask rcnn and detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.

Thank you for your time!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanggang001** [comment]
> Hello @zhanggang001,
> 
> **Extension of Refine Mask implementation**
> 
> I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask with **224*224** final size? The reason behind this question was that I work on very high resolution images and I get good results compare to mask rcnn, detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.
> 
> Thank you for your time!

Yeah, you can try that (add one more stage), but it will consume much more GPU memory.  Some tips to do that, using a class-agnostic classifier in the stages with large spatial size; reducing the feature channel; only upsampling the boundary pixels;  etc.  Good luck.

**Comment by apanand14** [comment]
Thank you for your answer. I will try those changes. I have to change your suggested chnages in config file mostly right? It would be helpful if you guide me more. Thank you in advance.

**Comment by zhanggang001** [comment]
> Thank you for your answer. I will try those changes. I have to change your suggested chnages in config file mostly right? It would be helpful if you guide me more. Thank you in advance.

you may also need to change the code.

**Comment by apanand14** [comment]
@zhanggang001, Thank you for your reply. May I know more about what code should I change to get 224*224 final mask size or more precise boundary pixels? or to use class-agnostic classifier only upsampling the boundary pixel and other parameters you mentioned above? I would appreciate your help in it.Thank you in advance.

**Comment by apanand14** [comment]
Hello @zhanggang001 , I'm able to run with the extended frame work with an extra stage. Not facing memory issue but yes, I agree that I'm able to train with batch size 1 only. I also tried your suggestions. The only thing I didn't understand is "upsampling boundary pixels". I would like to train with tweaking this parameter. Please guide me whenever you get time. Thank you in advance.

**Comment by FatmaMazen2021** [comment]
> Hello @zhanggang001,
> 
> **Extension of Refine Mask implementation**
> 
> I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask with **224*224** final size? The reason behind this question was that I work on very high resolution images and I get good results compare to mask rcnn, detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.
> 
> Thank you for your time!

Could you kindly share with me the steps to train refine mask on custom dataset?

**Comment by zhanggang001** [comment]
> > Hello @zhanggang001,
> > **Extension of Refine Mask implementation**
> > I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask with **224*224** final size? The reason behind this question was that I work on very high resolution images and I get good results compare to mask rcnn, detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.
> > Thank you for your time!
> 
> Could you kindly share with me the steps to train refine mask on custom dataset?

Please refer to [mmdetection v2.3.0](https://github.com/open-mmlab/mmdetection)

**Comment by TempleX98** [comment]
> Hello @zhanggang001,
> 
> **Extension of Refine Mask implementation**
> 
> I successfully ran your refine mask implementation and visualized results and it looks promising to me. Is it possible to extend framework for one more stage (stage 4) and produce mask with **224*224** final size? The reason behind this question was that I work on very high resolution images and I get good results compare to mask rcnn, detectron2 and normal mmdetection on my custom dataset but still it has some wobbly edges in some cases and would like to improve them. Your inputs will be helpful for the further improvements in my work.
> 
> Thank you for your time!

How do you fix it?
