### ISSUE TITLE
how to apply refine mask in cascade mask rcnn / HTC?

### ISSUE THREAD

**Issue by fuweifuvtoo** [zhanggang001/RefineMask#18]
hello!
thanks for your beautiful work.
I have a question that how to apply refine mask in cascade mask rcnn / HTC? 
Cause there are three stage in HTC, should I apply refine mask in the last stage or all the three stage?
thanks for your reply~

**Comment by zhanggang001** [comment]
> hello!
> thanks for your beautiful work.
> I have a question that how to apply refine mask in cascade mask rcnn / HTC?
> Cause there are three stage in HTC, should I apply refine mask in the last stage or all the three stage?
> thanks for your reply~

If for higher performance, you can apply refinemask with maximum output size 28 to the first two stages of HTC, and refinemask with maximum output size 112 to the last stage of HTC. You may need to set the loss weight of each stage on your own situation.

**Comment by fuweifuvtoo** [comment]
fine！that is helpful for me! Thanks a lot !!

Now I have another question
Can refinemask be used with mask scoring? Have you done a similar experiment?

thanks for your reply~

**Comment by zhanggang001** [comment]
> fine！that is helpful for me! Thanks a lot !!
> 
> Now I have another question
> Can refinemask be used with mask scoring? Have you done a similar experiment?
> 
> thanks for your reply~

Sure, it can be used with mask scoring. Please refer to the solution of the winner of the LVIS Challenge 2020. And the result of Table 10 in our paper (RefineMask) is got by applying RefineMask to this solution.

**Comment by fuweifuvtoo** [comment]
fine！ thanks a lot!
