### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by roar-1128** [zhanggang001/RefineMask#20]
Why are your datasets in PNG format and different from my datasets
The first data set of coco is 4134，31817, but mine is 9,25
can you give me a download path？
sorry about my so many question
look forward your response

**Comment by zhanggang001** [comment]
> Why are your datasets in PNG format and different from my datasets
> The first data set of coco is 4134，31817, but mine is 9,25
> can you give me a download path？
> sorry about my so many question
> look forward your response

I just use the data downloaded from [the official website](https://cocodataset.org/).

**Comment by roar-1128** [comment]
Thank you for your response.
