### ISSUE TITLE
How to get the “lvis_v0.5_val_cocofied.json”

### ISSUE THREAD

**Issue by AGanPoi** [zhanggang001/RefineMask#21]
I can‘t find this annotation file in LVIS offical website. Are this annotation generate by some methods?

**Comment by zhanggang001** [comment]
> I can‘t find this annotation file in LVIS offical website. Are this annotation generate by some methods?

tools/cocofied_lvis.py

**Comment by AGanPoi** [comment]
ok，thanks for your reply！

**Comment by AGanPoi** [comment]
It seems that offical LVIS website do not release the LVIS v0.5 datasets(as it's deprecated), so I could not find the "lvis_v0.5_train.json" and "lvis_v0.5_val.json". And I could not use "tools/cocofied_lvis.py" to map the annotation to coco format.
Because when I use "lvis_v1_val.json" to generate json, it occur an error "AssertionError: Results do not correspond to current LVIS set."
![1](https://user-images.githubusercontent.com/35792267/135008051-83957754-b172-4447-96f2-2159d068d88c.png)

**If you could just provide the "lvis_v0.5_val.json" or tell me where to download, very thanks!**

**Comment by zhanggang001** [comment]
> It seems that offical LVIS website do not release the LVIS v0.5 datasets(as it's deprecated), so I could not find the "lvis_v0.5_train.json" and "lvis_v0.5_val.json". And I could not use "tools/cocofied_lvis.py" to map the annotation to coco format.
> Because when I use "lvis_v1_val.json" to generate json, it occur an error "AssertionError: Results do not correspond to current LVIS set."
> ![1](https://user-images.githubusercontent.com/35792267/135008051-83957754-b172-4447-96f2-2159d068d88c.png)
> 
> **If you could just provide the "lvis_v0.5_val.json" or tell me where to download, very thanks!**

[lvis_v0.5_val.json](https://drive.google.com/file/d/1xRhYztx2t1YllFHenDdK-MzJWUpchb2P/view?usp=sharing)

Actually, you can filter out the images which are not in the coco validation set in lvis_v1_val_cocofiled.json to generate lvis_v0.5_val_cocofiled.json too.

**Comment by zhanggang001** [comment]
> > It seems that offical LVIS website do not release the LVIS v0.5 datasets(as it's deprecated), so I could not find the "lvis_v0.5_train.json" and "lvis_v0.5_val.json". And I could not use "tools/cocofied_lvis.py" to map the annotation to coco format.
> > Because when I use "lvis_v1_val.json" to generate json, it occur an error "AssertionError: Results do not correspond to current LVIS set."
> > ![1](https://user-images.githubusercontent.com/35792267/135008051-83957754-b172-4447-96f2-2159d068d88c.png)
> > **If you could just provide the "lvis_v0.5_val.json" or tell me where to download, very thanks!**
> 
> [lvis_v0.5_val.json](https://drive.google.com/file/d/1xRhYztx2t1YllFHenDdK-MzJWUpchb2P/view?usp=sharing)

**Comment by AGanPoi** [comment]
> > It seems that offical LVIS website do not release the LVIS v0.5 datasets(as it's deprecated), so I could not find the "lvis_v0.5_train.json" and "lvis_v0.5_val.json". And I could not use "tools/cocofied_lvis.py" to map the annotation to coco format.
> > Because when I use "lvis_v1_val.json" to generate json, it occur an error "AssertionError: Results do not correspond to current LVIS set."
> > ![1](https://user-images.githubusercontent.com/35792267/135008051-83957754-b172-4447-96f2-2159d068d88c.png)
> > **If you could just provide the "lvis_v0.5_val.json" or tell me where to download, very thanks!**
> 
> [lvis_v0.5_val.json](https://drive.google.com/file/d/1xRhYztx2t1YllFHenDdK-MzJWUpchb2P/view?usp=sharing)
> 
> Actually, you can filter out the images which are not in the coco validation set in lvis_v1_val_cocofiled.json to generate lvis_v0.5_val_cocofiled.json too.

Very thanks to your prompt reply！
