### ISSUE TITLE
mmdetection vs. detectron setting

### ISSUE THREAD

**Issue by SangbumChoi** [zhanggang001/RefineMask#28]
Hi thanks for the nice work.
I just wonder after seeing this issue https://github.com/SysCV/transfiner/issues/11#issuecomment-1105000739 it makes me to ask two questions

1. Is there any model from Table 8 (SOTA comparison) trained on detectron2?
2. Also normally mmdetection is run by EpochBasedRunner and detectron2 is run by iteration. (Additionally many different hyperparameter setting) Do you think default setting comapring between two libraray is fair comparison?

**Comment by zhanggang001** [comment]
> Hi thanks for the nice work. I just wonder after seeing this issue [SysCV/transfiner#11 (comment)](https://github.com/SysCV/transfiner/issues/11#issuecomment-1105000739) it makes me to ask two questions
> 
> 1. Is there any model from Table 8 (SOTA comparison) trained on detectron2?
> 2. Also normally mmdetection is run by EpochBasedRunner and detectron2 is run by iteration. (Additionally many different hyperparameter setting) Do you think default setting comapring between two libraray is fair comparison?

1. The models with ‡ were trained with a similar setting to detectron2 using mmdetection. The last sentence of the caption of Table 8 states this.
2. Most of the models in Table 1 and Table 8 we compared with (including Mask R-CNN, PointRend, HTC) were trained by ourselves with the same setting using mmdetection.
