### ISSUE TITLE
About simplehead

### ISSUE THREAD

**Issue by torchmyheart** [zhanggang001/RefineMask#30]
nice work ! I have a question about SimpleRefineMaskHead in refine_mask_head.py 
There is not mentioned in the article and README. May I ask how its performance is different from the normal model?
What changes have been made to the simple model
Looking forward to your reply！

**Comment by zhanggang001** [comment]
> nice work ! I have a question about SimpleRefineMaskHead in refine_mask_head.py There is not mentioned in the article and README. May I ask how its performance is different from the normal model? What changes have been made to the simple model Looking forward to your reply！

We simplified the implementation. The new one has less memory cost, faster training speed, and slightly better performance than the original implementation.

**Comment by torchmyheart** [comment]
Thanks a lot. If possible, could you briefly describe the difference in structure?

**Comment by zhanggang001** [comment]
> Thanks a lot. If possible, could you briefly describe the difference in structure?

No big changes in structure, just a better implementation.

**Comment by torchmyheart** [comment]
OK, got it

**Comment by 9p15p** [comment]
Hi, Dr. Zhang,
Thanks for your great work. 
Is there a best checkpoint for the faster-better-1x config
