### ISSUE TITLE
Where is pretrained model for 3x?

### ISSUE THREAD

**Issue by SangbumChoi** [zhanggang001/RefineMask#31]
Hi according to your paper all the highest AP was collected from 3x training which are denoted as $\ddagger$.
Can we get also the pretrained weight of those models? It would be grateful if we can have one to test.

Thanks :)

**Comment by zhanggang001** [comment]
Sorry, we did not keep models trained by the 3x schedule with the released codes. There is a model trained by someone else [here ](https://github.com/SysCV/transfiner/issues/11#issuecomment-1125017468).
