### ISSUE TITLE
CascadePSP Comparison

### ISSUE THREAD

**Issue by BrianPugh** [zhanggang001/RefineMask#7]
In your paper you don't compare against [CascadePSP](https://github.com/hkchengrex/CascadePSP). I was wondering if you could evaluate your method vs theirs? Thanks!

**Comment by zhanggang001** [comment]
​CascadePSP is a method towards class-agnostic and very high-resolution segmentation, but our work aims for high-quality general instance segmentation. So it is hard to compare these two works directly. We may apply our method to semantic segmentation in our future work.

**Comment by zhanggang001** [comment]
> In your paper you don't compare against [CascadePSP](https://github.com/hkchengrex/CascadePSP). I was wondering if you could evaluate your method vs theirs? Thanks!

​CascadePSP is a method towards class-agnostic and very high-resolution segmentation, but our work aims for high-quality general instance segmentation. So it is hard to compare these two works directly. We may apply our method to semantic segmentation in our future work.

**Comment by BrianPugh** [comment]
cascadepsp is essentially a binary mask refiner. They apply it to semantic segmentation by iteratively applying the network to each segmentation mask. See the "Quick Start" section of their readme.

**Comment by zhanggang001** [comment]
> cascadepsp is essentially a binary mask refiner. They apply it to semantic segmentation by iteratively applying the network to each segmentation mask. See the "Quick Start" section of their readme.

I know that. But our method aims for multi-class instance segmentation (instead of binary semantic segmentation) and is not a simple binary mask refiner. Applying it to semantic segmentation need more future work.

**Comment by BrianPugh** [comment]
So I guess I should clarify, in your paper you compare against mask-rcnn and other networks that are essentially tweaks to mask-rcnn. I'm asking if you can compare your results to mask-rcnn where each instance mask is individually refined by cascadepsp.

**Comment by zhanggang001** [comment]
> So I guess I should clarify, in your paper you compare against mask-rcnn and other networks that are essentially tweaks to mask-rcnn. I'm asking if you can compare your results to mask-rcnn where each instance mask is individually refined by cascadepsp.

Sure you can use CascadePSP in this way, but I may not do this comparison.  Two reasons: 1.As mentioned above, CascadePSP was initially proposed towards class-agnostic semantic segmentation;  2. According to my understanding, CascadePSP is a post-processing method (refine the initial mask in a cascade manner), but RefineMask is an end to end training method. These two methods are not closely related.

**Comment by BrianPugh** [comment]
cascadepsp isn't specific to semantic segmentation; its segmentation in general. And yes, it's a post-processing method. That said, the end goal of your paper and their paper is the same: high resolution masks, so I don't see how you can say that these methods are not closely related.

**Comment by zhanggang001** [comment]
> cascadepsp isn't specific to semantic segmentation; its segmentation in general. And yes, it's a post-processing method. That said, the end goal of your paper and their paper is the same: high resolution masks, so I don't see how you can say that these methods are not closely related.

OK. You are right, if the author of CascadePSP releases the instance segmentation results on COCO/LVIS/Cityscapes, we may add the comparison.
