### ISSUE TITLE
 model = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)报错

### ISSUE THREAD

**Issue by qzsrh** [zhanggang001/RefineMask#8]
在运行tools/train.py的时候
model = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)  这行代码报错：
 KeyError: 'RefineRoIHead is not in the head registry' 请问是什么原因呢？

**Comment by zhanggang001** [comment]
你直接运行python tools/train.py吗？如果是，参考/scripts/dist_train.sh导入环境变量
